---
apiVersion: v1
kind: Service
metadata:
  name: result-app-deployment-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
  selector:
    name: result-app-deployment
    author: standel
...